### ISSUE TITLE
change data linkage from render_template to webapi in flask

### ISSUE THREAD

**Issue by trnqltx** [trnqltx/jerboa#11]
# todo

- [x] craete function to get data in python 
- [x] allow 5000 port with load balancer
- [x] test (using IP address:5000)
- [x] create a sub domain (api.v-jerboa.com)
- [x] setting DNS A record

**Comment by trnqltx** [comment]
done !

<img width="565" alt="Screen Shot 2021-02-25 at 10 45 38" src="https://user-images.githubusercontent.com/54294808/109090634-a12e7000-7756-11eb-9e4e-b584cdaede09.png">
