### ISSUE TITLE
bar chart based on d3.js

### ISSUE THREAD

**Issue by trnqltx** [trnqltx/jerboa#15]
# todo

- [x] create sample.js for drawing a bar chart
- [x] modify index.html for sample.js
- [x] fix readme about usage
