### ISSUE TITLE
change connection port from default 5000 to 80

### ISSUE THREAD

**Issue by trnqltx** [trnqltx/jerboa#2]
# todo

- [x] allow http, https traffic
- [x] reject port 5000
- [x] fix docker run command ( -p 5000:5000 ->  -p 80:5000 )
- [x] remake docker container

**Comment by trnqltx** [comment]
done
