### ISSUE TITLE
add web server using nginx on docker

### ISSUE THREAD

**Issue by trnqltx** [trnqltx/jerboa#41]
## summary
- add web server using nginx on docker

## purpose
- separate AP server and WEB server

## todo

- [ ] pull docker image nginx latest
- [ ] create html, css, javascript files
- [ ] docker container run
- [ ] test
- [ ] docment ( fix readme)
