### ISSUE TITLE
fix to browse via HTTPS

### ISSUE THREAD

**Issue by trnqltx** [trnqltx/jerboa#5]
# todo

- [x] create an instance-group of gce
- [x] set up a load balancer
- [x] choice the google managed for SSL certificate
- [x] edit a DNS record for IP of load balancer

# check list

- [x] be used SSL certificate
- [x] v-jerboa.com -> https://v-jerboa.com
- [x] www.v-jerboa.com -> https://v-jerboa.com
- [x] http://v-jerboa.com -> https://v-jerboa.com
- [ ] http://www.v-jerboa.com -> https://v-jerboa.com

**Comment by trnqltx** [comment]
used SSL certificate
![File_000](https://user-images.githubusercontent.com/54294808/107133556-dfd9c300-692c-11eb-8c42-7ef00d77c324.png)

**Comment by trnqltx** [comment]
modify load balancer on GCP
